openapi: 3.0.0
info:
  title: RAG Chatbot API
  version: 1.0.0
paths:
  /chat:
    post:
      summary: Get a response from the RAG chatbot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The user's query.
                context:
                  type: string
                  description: The highlighted text from the book.
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The chatbot's response.
